<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LionFire.StateMachines.Abstractions\LionFire.StateMachines.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\LionFire.StateMachines\LionFire.StateMachines.csproj" />
    <ProjectReference Include="..\..\src\LionFire.StateMachines.Generation\LionFire.StateMachines.Generation.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
